feature: add range functionality to `fix_time`
ANNUBS/neurogym pull request #63
Opened 2024-09-30 12:51 UTC by gcroci2

2024-11-05 10:20 UTC, DaniBodor requested changes
Thanks for these options for the duration of the fixation time.
As commented below, I find the current implementation a bit confusing. I made a suggestion to offload those settings into a mixin class. What do you think of that idea?

2024-11-05 10:20 UTC, DaniBodor commented on neurogym/core.py
> +                    raise ValueError(msg)
this avoids printing the newline and indents in the error message.

```suggestion
                    msg = (
                        f"Invalid 'until' time for period {period}. Current max time: {self.tmax},",
                        f"Requested end time: {args}",
                    )
                    raise ValueError(msg)
```

2024-11-05 10:20 UTC, DaniBodor commented on neurogym/core.py
> +            self._duration[period] = duration
```suggestion
        self._duration[period] = duration
```

2024-11-05 10:20 UTC, DaniBodor commented on neurogym/envs/annubes.py
> +            Note that the duration of each input and output signal is increased by this time.
I have the impression that there is a bit too much going on in this one parameter. There are too many options to choose from.

Maybe add a mixin class for the fixation settings, something like this:

NB: it is unclear to me what the "until" and "callable" modes are.

```python
@dataclass
class FixationSettings:
    """Mix-in class for AnnubesEnv that specifies what the fixation period should look like.

    Args:
        intensity: Intensity during the fixation period.
        mode: Options are: "constant", "uniform", "choice", "truncated_exponential", "until".
        values: values to determine the length of the fixation period in ms.
            for "constant" or "until" modes, a single value is expected.
            for "uniform" mode, the min and max values of the uniform distribution to randomly choose from are expected.
            for "choice", a list of options to randomly choose from is expected.
            for "truncated_exponential" modes, a list of parameters for the distribution is expected.
            for "callable", a function is expected.
    """

    intensity: int | float = 0
    mode: Literal["constant", "uniform", "choice", "truncated_exponential", "until", "callable"] = "constant"
    values: float | tuple[float] | list[float] | Callable = 500

    def __post_init__(self):
        msg = ""
        single_value_expected = ["constant", "until"]
        if self.mode in single_value_expected:
            if not isinstance(self.values, float):
                msg = f"The {self.mode} mode expects a single value, but {self.values} ({type(self.mode)}) was given."

        elif self.mode == "callable":
            if not isinstance(self.values, Callable):
                msg = f"The {self.mode} mode expects a function, but {self.values} ({type(self.mode)}) was given."

        elif not isinstance(self.values, tuple | list):
            msg = f"The {self.mode} mode expects a list of values, but {self.values} ({type(self.mode)}) was given."

        if msg:
            raise ValueError(msg)
```

2024-11-18 10:56 UTC, gcroci2 commented on neurogym/envs/annubes.py
> +            Note that the duration of each input and output signal is increased by this time.
Such functionalities were already implemented within the core module (see [here](https://github.com/ANNUBS/neurogym/blob/29368d5f319e544b141b93867cd4227c43a4af29/neurogym/core.py#L236)), so I just added a docstring about them. I think that in the future we may want to improve this directly within the core module, but for now I'd use the functionality as it is.

2024-11-19 10:20 UTC, DaniBodor commented on neurogym/envs/annubes.py
> +            Note that the duration of each input and output signal is increased by this time.
I understand. At this point, the "until" and "callable" functionality are still unclear. Maybe add a few words explaining these?

2024-11-19 10:20 UTC, DaniBodor approved these changes
I'm approving this already, but please see my comment on the docstring.

2024-11-19 13:48 UTC, gcroci2 commented on neurogym/envs/annubes.py
> +            Note that the duration of each input and output signal is increased by this time.
I opened #69

2024-11-19 13:48 UTC, merged